### PR TITLE
Adding issues property to civic.json schema

### PR DESCRIPTION
**Pull request by mkalish**
This adds a new field where a url that points to where issues can be submitted.  Similar to the one in package.json.

### CODE REVIEW

**Comment by stvnrlly** [comment]
@mkalish Do you think that there are scenarios where the issue location is different than `github.com/owner/repo/issues`?

**Comment by mkalish** [comment]
@stvnrlly 
This came out of the conversation @trycrmr and I had about using the wafflie.io board to track issues for the various github projects which has a different URL

**Comment by stvnrlly** [comment]
Ah, nice. Is it possible that the existing `links` object could work here? That might allow for different combinations of sites, based on what a project needs/uses. We could also put continuous integration services in there, too. @emanuelfeld, do you have any feelings here?

As a side note: in the past, I've also left out information where it would take a standard format—like how Travis uses the `travis-ci.org/owner/repo` format—under the assumption that it's better to not rely on human-entered information when it can be inferred. But I don't know if that's the right approach, especially when a project may or may not use a particular resource.

**Comment by emanuelfeld** [comment]
I agree with your assessment, @stvnrlly. I think issues URLs should either be part of the links array or be used as the URL in the contact object.

**Comment by mkalish** [comment]
I'm fine with using the links then.  I'll go ahead and close this out.

**Pull request closed without merging**
